# Required For The Exit Message That Lets The User Know Their Password Has Been Found
import sys
# Required for md5!!
import hashlib
# Required for All Nested For Loops (Stored Seperately So That We Can Run All Of The Files Together)
from Cross_Check import *
# Global Vars:
stringPass = ""
# Functions:
def intro():
    print("Welcome to Password Crack!!!\n\n In this application, you will type a password into the console and Python will return an MD5 Hash of that password. Go ahead and copy that and then when Python asks you for the MD5 Hash, go ahead and Paste that into the console. ")
    print("Your md5 Hash is:", str(hashlib.md5(input("\n\nType your Password here: ").encode()).hexdigest()))
    main()
def main():
    inputMD5Hash = input("Paste your MD5 Hash here: ")
    print("Your MD5 Hash is: ", inputMD5Hash)
    print("Python shall now use Brute-Force to try an guess your password from the given MD5 String!")

    exec(open("Cross_Check\\bruteForce_a.py", "r").read())
    exec(open("Cross_Check\\bruteForce_b.py", "r").read())
    exec(open("Cross_Check\\bruteForce_c.py", "r").read())
    exec(open("Cross_Check\\bruteForce_d.py", "r").read())
    exec(open("Cross_Check\\bruteForce_e.py", "r").read())
    exec(open("Cross_Check\\bruteForce_f.py", "r").read())
    exec(open("Cross_Check\\bruteForce_g.py", "r").read())
    exec(open("Cross_Check\\bruteForce_h.py", "r").read())
    exec(open("Cross_Check\\bruteForce_i.py", "r").read())
    exec(open("Cross_Check\\bruteForce_j.py", "r").read())
    exec(open("Cross_Check\\bruteForce_k.py", "r").read())
    exec(open("Cross_Check\\bruteForce_l.py", "r").read())
    exec(open("Cross_Check\\bruteForce_m.py", "r").read())
    exec(open("Cross_Check\\bruteForce_n.py", "r").read())
    exec(open("Cross_Check\\bruteForce_o.py", "r").read())
    exec(open("Cross_Check\\bruteForce_p.py", "r").read())
    exec(open("Cross_Check\\bruteForce_q.py", "r").read())
    exec(open("Cross_Check\\bruteForce_r.py", "r").read())
    exec(open("Cross_Check\\bruteForce_s.py", "r").read())
    exec(open("Cross_Check\\bruteForce_t.py", "r").read())
    exec(open("Cross_Check\\bruteForce_u.py", "r").read())
    exec(open("Cross_Check\\bruteForce_v.py", "r").read())
    exec(open("Cross_Check\\bruteForce_w.py", "r").read())
    exec(open("Cross_Check\\bruteForce_x.py", "r").read())
    exec(open("Cross_Check\\bruteForce_y.py", "r").read())
    exec(open("Cross_Check\\bruteForce_z.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capA.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capB.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capC.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capD.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capE.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capF.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capG.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capH.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capI.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capJ.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capK.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capL.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capM.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capN.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capO.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capP.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capQ.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capR.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capS.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capT.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capU.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capV.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capW.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capX.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capY.py", "r").read())
    exec(open("Cross_Check\\bruteForce_capZ.py", "r").read())
    exec(open("Cross_Check\\bruteForce_1.py", "r").read())
    exec(open("Cross_Check\\bruteForce_2.py", "r").read())
    exec(open("Cross_Check\\bruteForce_3.py", "r").read())
    exec(open("Cross_Check\\bruteForce_4.py", "r").read())
    exec(open("Cross_Check\\bruteForce_5.py", "r").read())
    exec(open("Cross_Check\\bruteForce_6.py", "r").read())
    exec(open("Cross_Check\\bruteForce_7.py", "r").read())
    exec(open("Cross_Check\\bruteForce_8.py", "r").read())
    exec(open("Cross_Check\\bruteForce_9.py", "r").read())
    exec(open("Cross_Check\\bruteForce_0.py", "r").read())
    exec(open("Cross_Check\\bruteForce_exc.py", "r").read())
    exec(open("Cross_Check\\bruteForce_@.py", "r").read())
    exec(open("Cross_Check\\bruteForce_hash.py", "r").read())
    exec(open("Cross_Check\\bruteForce_$.py", "r").read())
    exec(open("Cross_Check\\bruteForce_%.py", "r").read())
    exec(open("Cross_Check\\bruteForce_^.py", "r").read())
    exec(open("Cross_Check\\bruteForce_&.py", "r").read())
    exec(open("Cross_Check\\bruteForce_(.py", "r").read())
    exec(open("Cross_Check\\bruteForce_).py", "r").read())
    exec(open("Cross_Check\\bruteForce_-.py", "r").read())
    exec(open("Cross_Check\\bruteForce_=.py", "r").read())
    exec(open("Cross_Check\\bruteForce__.py", "r").read())
    exec(open("Cross_Check\\bruteForce_+.py", "r").read())
    exec(open("Cross_Check\\bruteForce_,.py", "r").read())
    exec(open("Cross_Check\\bruteForce_..py", "r").read())
    exec(open("Cross_Check\\bruteForce_fs.py", "r").read())
    exec(open("Cross_Check\\bruteForce_;.py", "r").read())
    exec(open("Cross_Check\\bruteForce_'.py", "r").read())
    exec(open("Cross_Check\\bruteForce_[.py", "r").read())
    exec(open("Cross_Check\\bruteForce_].py", "r").read())
    exec(open("Cross_Check\\bruteForce_bs.py", "r").read())
    exec(open("Cross_Check\\bruteForce_&lt;.py", "r").read())
    exec(open("Cross_Check\\bruteForce_&gt;.py", "r").read())
    exec(open("Cross_Check\\bruteForce_qm.py", "r").read())
    exec(open("Cross_Check\\bruteForce_sc.py", "r").read())
    exec(open("Cross_Check\\bruteForce_qtd.py", "r").read())
    exec(open("Cross_Check\\bruteForce_{.py", "r").read())
    exec(open("Cross_Check\\bruteForce_}.py", "r").read())
    exec(open("Cross_Check\\bruteForce_strlne.py", "r").read())
    exec(open("Cross_Check\\bruteForce_`.py", "r").read())
    exec(open("Cross_Check\\bruteForce_~.py", "r").read())
    exec(open("Cross_Check\\bruteForce_space.py", "r").read())
# Function To Be Called If A Match Is Found
def success():
    # Simple Exit Program With Message That Says Password Was Found!
    sys.exit("\n\n\n\n\n\n\n\n\n\n\n\n\nPython found your password to be \"" + stringPass + "\"!!!")

# Initiate Program
intro()